
export const GET_PLAYLIST_SONGS = 'GET_PLAYLIST_SONGS';
export const GET_PLAYLIST_SONGS_SUCCESS = 'GET_PLAYLIST_SONGS_SUCCESS'

export const SAVE_PLAYLIST = 'SAVE_PLAYLIST';
export const SAVE_PLAYLIST_SUCCESS = 'SAVE_PLAYLIST_SUCCESS';
export const SAVE_PLAYLIST_ERROR = 'SAVE_PLAYLIST_ERROR';


export const GET_PLAYLIST = 'GET_PLAYLIST';
export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS';
export const GET_PLAYLIST_ERROR = 'GET_PLAYLIST_ERROR';


export const SPOTIFY_LOGIN = 'SPOTIFY_LOGIN';
export const SPOTIFY_LOGIN_ERROR = 'SPOTIFY_LOGIN_ERROR';
export const SET_TOKEN = 'SET_TOKEN';
